### ISSUE TITLE
Bug: Too many open files: No file descriptors available @ rb_sysopen

### ISSUE THREAD

**Issue by ahollmann** [andrcuns/allure-report-publisher#651]
Thanks for the work on this useful tool.

I've encountered a bug due to too many open files. 

Successful run with: allure-results/: found 65367 matching artifact files and directories
Failed run: with: allure-results/: found 69662 matching artifact files and directories

The limit on open file descriptors within the container is:

```
ulimit -Sn
65536
```

It seems that allure-report-publisher opens all files before uploading to S3 and runs into a file descriptor limit.

Increasing the file descriptor limit using `ulimit -Sn 1048576` made it work until a hard file limit will be hit.

It would be great to limit the number of concurrently opened files in the code.

Here is the log output:

```
[2024-02-28 12:23:38 +0000] Generated allure report. Out: Report successfully generated to /tmp/allure-report-1709122973
[2024-02-28 12:23:38 +0000] Removing duplicate entries in '/tmp/allure-report-1709122973/widgets/executors.json'
[✖] uploading ... failed
No file descriptors available @ rb_sysopen - /tmp/allure-report-1709122973/data/test-cases/99029f291acc5e61.json
== DEBUG LOG OUTPUT ==
[2024-02-28 12:23:38 +0000] Uploading report files
[2024-02-28 12:23:43 +0000] Error: No file descriptors available @ rb_sysopen - /tmp/allure-report-1709122973/data/test-cases/99029f291acc5e61.json
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/uploaders/s3.rb:118:in `initialize'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/uploaders/s3.rb:118:in `new'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/uploaders/s3.rb:118:in `block in upload_to_s3'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/uploaders/s3.rb:116:in `map'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/uploaders/s3.rb:116:in `upload_to_s3'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/uploaders/s3.rb:77:in `upload_report'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/uploaders/_uploader.rb:66:in `upload'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/commands/upload.rb:188:in `block in upload_report'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/helpers/spinner.rb:37:in `spin'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/lib/helpers/spinner.rb:28:in `spin'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/commands/upload.rb:188:in `upload_report'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/lib/allure_report_publisher/commands/upload.rb:97:in `call'
/usr/local/bundle/gems/dry-cli-1.0.0/lib/dry/cli.rb:116:in `perform_registry'
/usr/local/bundle/gems/dry-cli-1.0.0/lib/dry/cli.rb:65:in `call'
/usr/local/bundle/gems/allure-report-publisher-3.1.0/exe/allure-report-publisher:7:in `<top (required)>'
/usr/local/bundle/bin/allure-report-publisher:25:in `load'
/usr/local/bundle/bin/allure-report-publisher:25:in `<main>'
== DEBUG LOG OUTPUT ==
```

**Comment by YarLyashenko** [comment]
encountered the same issue

**Comment by andrcuns** [comment]
I wonder if it's either google client or the parallel gem that keeps the files open. I'll try to take a look in the following week, haven't had the usecase of handling such large reports myself.

**Comment by YarLyashenko** [comment]
It is not about the size. I hit this with small reports. Ulimit value inside the image andrcuns/allure-report-publisher:3.1.0 running at my enterprise gitlab is 1000.

**Comment by YarLyashenko** [comment]
@andrcuns thanks for the fix.

**Comment by ahollmann** [comment]
@andrcuns Thanks for the quick implementation of the fix.
